DefaultContentLanguage = "en"
Paginate = 3
SectionPagesMenu = "main"
baseURL = "https://blue-dune-0818ed300.azurestaticapps.net"
enableRobotsTXT = true
googleAnalytics = "UA-116059715-1"
languageCode = "en-us"
theme = "ananke"
title = "Carnelian Craft"
[markup.goldmark.renderer]
unsafe = true
[[menu.main]]
name = "Free Patterns"
url = "/tags/free-patterns/"
weight = 2
[params]
background_color_class = "bg-carnelian"
body_classes = "bg-near-white"
custom_css = ["css/site.css"]
description = "Embroidery and cross stitch // patterns and hoop art // reviews and events"
facebook = "https://www.facebook.com/carneliancraft"
favicon = ""
featured_image = "/img/home-splash.jpg"
github = ""
gitlab = ""
instagram = "https://www.instagram.com/carnelian_craft/"
linkedin = ""
mastodon = ""
recent_posts_number = 2
rss = ""
site_logo = "/img/logo.png"
slack = ""
stackoverflow = ""
twitter = ""
youtube = ""
[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = 0.5
[taxonomies]
tag = "tags"
